# Generated by Django 6.0.6 on 2026-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_booking_booked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
    ]
