# Generated by Django 6.0.6 on 2026-07-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
